### ISSUE TITLE
Switch from OTBS to K&R indent style

### ISSUE THREAD

**Issue by rodebert** [nikita-kit/nikita-js#1]
Consider switching the style of indentation. 

Your are referring to [Javascript the good parts](http://www.amazon.com/exec/obidos/ASIN/0596517742) from [Douglas Crockford](http://en.wikipedia.org/wiki/Douglas_Crockford) in witch he states:

> I always use the K&R style, putting the { at the end of a line instead of the front, because it avoids a horrible design blunder in JavaScript's return statement.

He refers to:

```
return {
   success: true
};
```

and:

```
return 
{
    success: true
};
```

The first one will return an object with a succes property. The latter will return undefined because of semicolon insertion.

**Comment by rodebert** [comment]
@axten Why is this closed without giving a reason?

**Comment by DracoBlue** [comment]
He recreated the entire coding standard in https://github.com/nikita-kit/nikita-js/tree/coding-standard

This will be merged soon.
