### ISSUE TITLE
There are no classes in Javascript

### ISSUE THREAD

**Issue by rodebert** [nikita-kit/nikita-js#2]
There are no classes in Javascript. What you are defining as a class are prototypes and they are not [classes](http://raganwald.com/2014/01/19/prototypes-are-not-classes.html). 

Even the introduction of the classes in ES6 is no real OOP implementation as it is only syntactic sugar to define custom types. 

Javascript does [not](http://www.nczonline.net/blog/2012/10/16/does-javascript-need-classes/) need classes.

**Comment by rodebert** [comment]
@axten Why is this closed without giving a reason?

**Comment by DracoBlue** [comment]
He recreated the entire coding standard in https://github.com/nikita-kit/nikita-js/tree/coding-standard

This will be merged soon.
