### ISSUE TITLE
coding style fails jslint analysis

### ISSUE THREAD

**Issue by m-schimmelpfennig** [nikita-kit/nikita-js#3]
the coding style mentioned in README.md fails jslint code analysis:
- openen brackets should be behind a declatation
- var decalarations should be combined

... and some others according lintjs

**Comment by DracoBlue** [comment]
We should use jshint for that. Can we work out a proper jshint.rc for the
Codingstandards?

Am Dienstag, 4. August 2015 schrieb m-schimmelpfennig :

> the coding style mentioned in README.md fails jslint code analysis:
>
>    - openen brackets should be behind a declatation
>    - var decalarations should be combined
>
> ... and some others according lintjs
>
> Reply to this email directly or view it on GitHub
> <https://github.com/nikita-kit/nikita-js/issues/3>.
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
https://github.com/nikita-kit/generator-nikita/blob/master/.jshintrc this file should be updated
